### ISSUE TITLE
new feature: add Firebase Performance

### ISSUE THREAD

**Issue by alexodus** [Larpon/QtFirebase#10]
...and upgrade to firebase 4.0, thanks!

**Comment by Larpon** [comment]
@alexodus - we can only add support for Firebase features that's implemented via their C++ SDK.

I just had a quick look at [the feature table](https://firebase.google.com/docs/cpp/setup) - and can't spot any Performance related libs. Maybe you know if it's build into some of the other libs in the list?

Have you tried building against Firebase 4.0? (Google spit out new versions faster than I can test them :) )
Unless they've made major changes to the API it should run

**Comment by Larpon** [comment]
You can use at least version `4.0.1` of the Firebase C++ SDK if you update the following:

Update some of the packages in the `Extras` section in `Android SDK Manager`:
![image](https://user-images.githubusercontent.com/768942/27610952-a2037de4-5b90-11e7-8334-fe2d2ccc9cb8.png)

### You don't need to update anything else in `Android SDK Manager` - updating the Android SDK package might break Qt's building process depending on your Qt version!

Bump versions in `build.gradle`
```
buildscript {
   ...
    dependencies {
        ...
        classpath 'com.google.gms:google-services:3.1.0'
    }
}

dependencies {
    ...
    compile 'com.google.android.gms:play-services-base:11.0.0'  // Mandatory - Firebase rely on Google Play services

    compile 'com.google.firebase:firebase-ads:11.0.0'           // For AdMob support
    compile 'com.google.firebase:firebase-analytics:11.0.0'     // For Google Analytics support
    compile 'com.google.firebase:firebase-config:11.0.0'        // For RemoteConfig support
}
```

Finally in your `AndroidManifest.xml` you should set your `Minimum required SDK` to >= 14:
```
<uses-sdk android:minSdkVersion="14" ... />
```

I'll add this to the project readme's when I can

**Comment by Larpon** [comment]
Wrong issue id - was #10 from QtFirebaseExample - just ignore the above reference
