### ISSUE TITLE
Add support for arm64-v8a

### ISSUE THREAD

**Issue by MasterMind2k** [Larpon/QtFirebase#102]
With Qt 5.12 we got builds for arm64-v8a.

When trying to build my project with QtFirebase I received a lot of "ambiguous" compiler errors coupled with implicit conversions warnings (all together 47).

**Comment by Larpon** [comment]
This is only possible if Google has (or adds) support for this architecture.
Try raising an issue [here](https://github.com/firebase/quickstart-cpp/issues) and see what they say

**Comment by khoaopentechiz** [comment]
hi @Larpon what do you mean by google support for this architecture? do you mean in order to build a qt app that has QtFirebase for arm64, the firebase c++ sdk should support this architecture?

**Comment by Larpon** [comment]
@MasterMind2k + @khoaopentechiz 
Sorry - my bad - I had a old SDK confusing me. I guess it should work then.
@MasterMind2k could you maybe paste a few essential lines from the error you're getting to get us started? It could be something simple like a wrong `ARCH` define somewhere.

**Comment by MasterMind2k** [comment]
Some lines:
```
/QtFirebase/src/qtfirebaseservice.cpp:185:20: error: ambiguous conversion for functional-style cast from 'int64_t' (aka 'long') to 'QVariant'

/QtFirebase/src/qtfirebaseremoteconfig.cpp:230:45: error: use of overloaded operator '=' is ambiguous (with operand types 'QVariant' and 'int64_t' (aka 'long'))
                updatedParameters[it.key()] = remote_config::GetLong(it.key().toUtf8().constData());
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

But, simply by building with latest Qt 5.12.3 against latest Android NDK, you should get these errors.

**Comment by MasterMind2k** [comment]
Oh, and yes. You **need** to use the clang compiler! The gnustl won't work anymore.

**Comment by Larpon** [comment]
Closing this as I get no compile errors after [this commit](https://github.com/Larpon/QtFirebase/commit/41f42e6c5a5d45d707dfe72ee820509035633854).
