### ISSUE TITLE
Building on Windows : firebase/app.h not found

### ISSUE THREAD

**Issue by saperlipopette45** [Larpon/QtFirebase#105]
Hello, 

I've been using QtFirebase on Android and iOS successfully, but since QtFirebase integration, my builds do not work anymore on Windows. I get the following error :

`firebase/app.h not found`

Any idea ?

**Comment by adolby** [comment]
firebase/app.h is a file that needs to be included for the C++ Firebase API. This is likely an issue with the compiler not finding the include path in your firebase_cpp_sdk folder.

The QtFirebase project is expecting the firebase_cpp_sdk folder downloaded from Google Firebase to be inside the project's top level folder (QtFirebase) or it can be set with the environment variable QTFIREBASE_SDK_PATH.

**Comment by Larpon** [comment]
@saperlipopette45 - any updates?
Otherwise I'll close this next time there's housekeeping :smile:
