### ISSUE TITLE
How to specify banner size  (or AdSize), in particular 'SMART_BANNER' ? 

### ISSUE THREAD

**Issue by ElderOrb** [Larpon/QtFirebase#107]
I want banner to use most of the screen except small area at the bottom. Specifying width/height didn't help - I was getting 320x50.

**Comment by Larpon** [comment]
@ElderOrb hey!
If I understand [this](https://developers.google.com/admob/android/banner#banner_sizes) correctly
`SMART_BANNER` will only adapt to `screen.width` and a height of any one of `32, 50, 90` - I'm not sure you can have 100% custom width x height?

**Comment by ElderOrb** [comment]
Oookay, let it be 90 then. How to enable SMART_BANNER for height 90? As I said specifying height didn't work for me

**Comment by ElderOrb** [comment]
So no solution at the moment?

**Comment by Larpon** [comment]
No time to investigate from my side unfortunately - sorry! I'm sure it worked when I implemented it way back.

**Comment by Larpon** [comment]
Are you setting width / height after initialization? Try having the values set when the QML element is instanciated

**Comment by edips** [comment]
[Here](https://github.com/FalsinSoft/QtAndroidTools/blob/f49b384129a80e93655e212b87bb6da5aecebc2b/QtAndroidTools/QAndroidAdMobBanner.h) is an example of banner types in cpp from QtAndroidTools project.

**Comment by ElderOrb** [comment]
@edips thanks, but this is purely admob-based integration, I'm more curious on how to get smart banners via firebase

**Comment by Larpon** [comment]
It was (is still) [working](https://github.com/Larpon/DeadAscend/blob/5039c0ff0eb9147a33d59dab242e88a87ada2090/App/main.qml#L202) in the latest build of Dead Ascend
