### ISSUE TITLE
Child of child

### ISSUE THREAD

**Issue by panmareksadowski** [Larpon/QtFirebase#115]
How can I retrieve child of child? Supposed that I have database:
```javascript
{
"child1":{
    "child2":{
        "property1":"value"
    }
}
```
I tried in qml `request.child("child1").child("child2").exec()`, where request is `DatabaseRequest`. Than snapshot.exists() is always `false`.

**Comment by Larpon** [comment]
I'm not very well experienced with the Database module - but have you tried giving `child` a [path-like string](https://github.com/Larpon/QtFirebase/blob/7e8f81235266db3a40caf00bad707501177f9a22/src/qtfirebasedatabase.cpp#L231)?

maybe something like (... and this is pulled out of thin air):
`request.child('child1/child2')`

**Comment by panmareksadowski** [comment]
Yes, it works.
