### ISSUE TITLE
No rule to make target

### ISSUE THREAD

**Issue by AriosJentu** [Larpon/QtFirebase#118]
I have an interesting bug, It was posted more than one year ago (https://github.com/Larpon/QtFirebaseExample/issues/10), and now I've got something same as this.
When building mine project to desktop, it works good, but when I build it for android, I've got next issue in issues tab of QT Creator:
`:-1: error: No rule to make target '/home/arios/QT Projects/QtExtensions/QtFirebase/firebase_cpp_sdk/libs/android/arm64-v8a/c++/libfirebase_app.a', needed by 'libCalendar.so'.  Stop.`
I thought - maybe I do something wrong with my _build.gradle_, and I've tried to build your QtFirebaseExample project, and I've got same error:
`:-1: error: No rule to make target '/home/arios/QT Projects/QtExtensions/QtFirebase/firebase_cpp_sdk/libs/android/arm64-v8a/c++/libfirebase_app.a', needed by 'libApp.so'.  Stop.` 
Maybe I'm doing something wrong?
Qt Creator - 4.9.2
Qt - 5.13.0
(All configs of your current project, I haven't change anything except directory for include QTFirebase project in App.pro)
firebase_cpp_sdk - 6.2.0

**Comment by AriosJentu** [comment]
Solved with replacing to SDK 6.1.0 and fixing directiories. Now build shows errors when building for Android (Error 4 when building APK), but I think, it's for another issue.

**Comment by Larpon** [comment]
@AriosJentu hi and welcome!
Hmm it could seem like things have moved around again. This wouldn't be the first time they did this 😀
