### ISSUE TITLE
Running the project and take advantages of it for my own project

### ISSUE THREAD

**Issue by ghost** [Larpon/QtFirebase#120]
Hello all,

I'm going to develop an Android app with the following description, but wanted to test this project on my Android device in advance to figure out what it does exactly! When built using the android kit on Qt Creator 4.9.1 on Windows, I get **this error**:

_FAILURE: Build failed with an exception.
* Where:
Settings file 'D:\Projects\QML\QtFirebaseExample-master\build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_12_3_for_Android_ARMv7-Debug\android-build\settings.gradle' line: 32
* What went wrong:
A problem occurred evaluating settings 'android-build'.
> Firebase C++ SDK directory /home/lmp/Projects/QtFirebaseExample/extensions/QtFirebase/firebase_cpp_sdk does not exist
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org_

**My project description**:

Simply, I want to develop an app for Android devices, front-end with QML and back-end with C++, when installed and logged in successfully, it can send packages to Firebase (with write/read access) and when not logged in, it has only read access to the packages. Each package is actually a set of data: a _text_, an _int_ number and an _image_ denoting a product (for instance: _Name of product_: "laptop TH 950", _Price_: $ 550, _Picture_: "The laptop’s image").

Now my question is what exactly do I need to develop my app, please?

**Comment by Larpon** [comment]
@Frankyth hey and welcome to the community 👋😃

I can't give much help regarding your project and can only say that QtFirebase and Qt development in general requires some programming experience - how much or how little is hard to say 🙂

I can see that this message:
```

**Comment by Larpon** [comment]
Sorry - hit the wrong button 😀

**Comment by Frankyth** [comment]
Hi And thanks so much. 
Wow, I must say I'm super glad that I can get rid of those numerous steps and files harder than "rocket science" and stick to [this section](https://github.com/Larpon/QtFirebaseExample/blob/master/App/platforms/android/gradle.properties)

I found the file: _D:\Projects\QML\QtFirebaseExample-master\QtFirebaseExample-master\App\platforms\android\gradle.properties_. But how to open it to be able to edit it!?

Also I downloaded _firebase_cpp_sdk_6.2.0_ (unzipped 2.9 GB) and copied it to the Android SDK folder.

**Comment by Larpon** [comment]
@Frankyth providing support on how to open and edit *text* files on your platform is beyond the scope of this project and not good use of the community's time.

Searching on Google and StackOverflow will get you very far in this regard.

I strongly suggest your get to know your platform and development tools before diving head-straight into projects like this 🙂

**Comment by Frankyth** [comment]
Sorry. The files ended in .properties were new for me that was why I asked this. 

My .properties file contains this: _systemProp.firebase_cpp_sdk.dir=/home/lmp/Projects/QtFirebaseExample/extensions/QtFirebase/firebase_cpp_sdk
systemProp.ndk_dir=/home/lmp/Environments/Android/android-ndk-current_


There are two paths in the file. Should I edit it and give each its specific path to _firebase_cpp_sdk_ in SDK and NDK, respectively?

**Comment by Larpon** [comment]
> Sorry. The files ended in .properties were new for me that was why I asked this.

It wasn't meant as something rude - just a reminder to try out your options before asking :smiley:

The error you're getting comes from the Android SDK (I.e. not QtFirebase related) - and as it says you need to agree to some licenses - this is something all Android developers must do. Try Google for the specific lines in the error message

**Comment by Frankyth** [comment]
Yes, it was done and nearly reaching the end to create the APK file but showed this error:

_FAILURE: Build failed with an exception.
 What went wrong:
Execution failed for task ':transformClassesWithMultidexlistForDebug'.
com.android.build.api.transform.TransformException: Error while generating the main dex list.
 Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Get more help at https://help.gradle.org_

I'm not sure what modification is the right one to choose for the file **build.gradle** to get rid of this last difficulty and whether it's also right for the forthcoming projects I will probably be dealt with.

**Comment by Frankyth** [comment]
I made these changes:
**1)** Edited the file **local.properties** to this:
_ndk.dir=D:/Qt_Stuff/android-ndk-r19c
sdk.dir=D:/Qt_Stuff/Sdk_

**2)** Changed the file **build.gradle** from:

_implementation 'com.google.firebase:firebase-core:16.0.1'
implementation 'com.google.firebase:firebase-messaging:17.1.0'_

To:

_implementation 'com.google.firebase:firebase-core:15.0.2'
implementation 'com.google.firebase:firebase-messaging:15.0.2'_

And the re-built the project for Anrdoid Arm7. Still the same error! :(

_FAILURE: Build failed with an exception.
 What went wrong:
Execution failed for task ':transformClassesWithMultidexlistForDebug'.
 com.android.build.api.transform.TransformException: Error while generating the main dex list.
 Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 Get more help at https://help.gradle.org_

Why should that project be that complicated just to build!? It's really astonishing.

**Comment by Larpon** [comment]
> Why should that project be that complicated just to build!? It's really astonishing.
Because you're relying on a huge stack of software - and software is not always straight forward :slightly_smiling_face:

What version of Java have you installed on your system?

**Comment by Frankyth** [comment]
Dear Larpon, I'm myself a programmer of C++ which is the most complex (and best) programming language, so I'm not a newbie in this case! What I say, almost all projects I've downloaded on GitHub have not made the tester go through several steps just to run the project! :)

Anyhow, back to the question: 
I think this image gives you the info on all my Android settings:
https://imgur.com/gpsnSPe

**Comment by Larpon** [comment]
Sorry, the picture is too lowres for me to see the Java version from.

FYI You can paste images directly on GitHub input fields instead of using 3rd party services like imgur.

**Comment by Larpon** [comment]
Anyway that error message can be because you're running a Java version < 8. Gradle rely on Java

**Comment by Frankyth** [comment]
Ow, right. Thanks. From now on I will upload my images right to here! :)
The Java version my Qt Creator is using is: **jdk1.8.0_211**. 
Should I use a more updated version of it?

**Comment by Larpon** [comment]
> Should I use a more updated version of it?

JDK 1.8.x should be fine. The problem is maybe somewhere else then.

**Comment by Frankyth** [comment]
I really don't know where to seek more! :(
There's also this module error in all _qml_ files. Here in _Main.qml_:

![3](https://user-images.githubusercontent.com/52600929/61574832-2e6d0580-aada-11e9-847e-73eb7b15bc11.PNG)

**Comment by Larpon** [comment]
I can see from that screenshot that QtFirebase is not getting included. Please check the path to `qtfirebase.pri` in the `App.pro` file...

**Comment by Larpon** [comment]
Exactly

**Comment by Frankyth** [comment]
1) So it is included. Then why is there that "not found" error there and why can't I build the project successfully, please? 

2) I also just thought of the api level for the android build. It's 29. Could it be the source for the error "_Execution failed for task ':transformClassesWithMultidexlistForDebug'._" error?

3) Also one other question: Is it the only example Firebase is used in QML in the world? If there's a simpler example I can run and figure out properly and probably take benefits of that form my own project, I had better go for that instead.

**Comment by SobolevWladimir** [comment]
Hey. I have the same error. Execution failed for task ':transformClassesWithMultidexlistForDebug'." error
There is a solution ?

**Comment by Larpon** [comment]
Try using Firebase C++ SDK v6.1.0

[See solutions here](https://github.com/Larpon/QtFirebaseExample/issues/19#issuecomment-518782261)
