### ISSUE TITLE
Build fails: Undeclared identifier 'qFirebaseDb'

### ISSUE THREAD

**Issue by sdzurenko** [Larpon/QtFirebase#125]
QtFirebase version  1.4.2
Google SDK version  1.6.0
iOS target build

Clean builds fail with the error:

../../src/qtfirebase_plugin.cpp:35:12: error: use of undeclared identifier 'qFirebaseDb'
    return qFirebaseDb;

If I set QTFIREBASE_CONFIG to not build database:

QTFIREBASE_CONFIG = admob analytics messaging remote_config auth

the build succeeds.  If I put database back in:

QTFIREBASE_CONFIG = admob analytics messaging remote_config auth database

the build succeeds.  The "undeclared identifier" error goes away.

I have recursively grep'ed for qFirebaseDb under QtFirebase, Google C++ SDK, and Google iOS Frameworks.  qtfirebase_plugin.cpp  is the only place that name occurs.  Why does the QtFirebaseDatabaseProvider function return the undeclared identifier qFirebaseDb?

**Comment by Larpon** [comment]
That sounds like a bug indeed
