### ISSUE TITLE
Undefined symbol "_OBJC_CLASS_$_GDTTransport" (iOS)

### ISSUE THREAD

**Issue by demiantres** [Larpon/QtFirebase#126]
With the latest Firebase SDK 6.6.0 the following compiler error appears when using the analytics module:

Undefined symbol "_OBJC_CLASS_$_GDTTransport"

**Comment by demiantres** [comment]
Removing the FirebaseCoreDiagnostics framework seems to fix the problem.

**Comment by Larpon** [comment]
@demiantres - thanks for reporting both error and fix.

We're a little behind with the testing of the recent C++ SDKs. It moves faster than I can get to test on all platforms at the moment
