### ISSUE TITLE
Usage of Advertising Identifier

### ISSUE THREAD

**Issue by sdzurenko** [Larpon/QtFirebase#127]
Hi,
I'm attempting to submit an update of my app to the Apple Store which includes AdMob ads via the QtFirebase AdMob QML interface.  I'm getting the following message from Apple:

> Does this app use the Advertising Identifier (IDFA)?
> The Advertising Identifier (IDFA) is a unique ID for each iOS device and is the only way to offer targeted ads. Users can choose to limit ad targeting on their iOS device.
> 
> If your app is using the Advertising Identifier, check your code—including any third-party code—before you submit it to make sure that your app uses the Advertising Identifier only for the purposes listed below and respects the Limit Ad Tracking setting. If you include third-party code in your app, you are responsible for the behavior of such code, so be sure to check with your third-party provider to confirm compliance with the usage limitations of the Advertising Identifier and the Limit Ad Tracking setting.

Apple proceeds to tell me that my app is indeed using the Advertising Identifier and asks me to confirm the following:

> I confirm that this app, and any third party that interfaces with this app, uses the Advertising Identifier checks and honors a user's Limit Ad Tracking setting in iOS and, when it is enabled by a user, this app does not use Advertising Identifier, and any information obtained through the use of the Advertising Identifier, in any way other than for "Limited Advertising Purposes" as defined in the iOS Developer Program License Agreement.

So my question... Does QtFirebase do anything with the IDFA, or is that buried in the Google Firebase code? Do you know anything about the IDFA? Do you know if the Limit Ad Tracking setting in iOS is honored?

Thanks for any help you can provide!

**Comment by Larpon** [comment]
That's burried in Google's Firebase SDK either the C++, iOS or both. I had to Google and ended up on Stackoverflow if I remember correctly. I'm sorry but I can't give any legal advices on what to do etc.

**Comment by sdzurenko** [comment]
Yeah, I did some searching as well and I'm fairly confident that Google Firebase handles the Limit Ad Tracking appropriately.  I just wanted to find out from you if your wrappers do anything specific with IDFA or Ad Tracking.  If not, then I think I'm good.  

Thanks for the quick reply!

**Comment by Larpon** [comment]
Awesome, 
Correct - no QtFirebase code uses any such thing 🙃

**Comment by sdzurenko** [comment]
Just to close the loop on this issue, Apple already accepted my update, which I just downloaded from the App Store.  Ads are showing!  So you can add another "real world" app to your list of apps using QtFirebase "in the wild."

Thanks for your help!
