### ISSUE TITLE
Android build target 28

### ISSUE THREAD

**Issue by demiantres** [Larpon/QtFirebase#131]
Google Play requests build target 28 (afaik) now. I had some problems with the compilation first. Maybe the following can be added to the docs:

1.) Add to **gradle.properties** file:
`android.useAndroidX=true
android.enableJetifier=true`

2.) Eventually remove this from **build.gradle**:
`implementation 'com.android.support:appcompat-v7:+'`

**Comment by Larpon** [comment]
@demiantres - thanks for posting this!
I'll check and include when I have time to test it - what Firebase C++ SDK version are you using??

**Comment by demiantres** [comment]
The latest one (6.4.0).

**Comment by Larpon** [comment]
Thanks!

**Comment by Larpon** [comment]
QtFirebase + Example now builds with latest master and Firebase C++ SDK 6.7.0. Thanks for your input!
