### ISSUE TITLE
Build Failed for Android: Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForDebug'.

### ISSUE THREAD

**Issue by piyushverma** [Larpon/QtFirebase#133]
Hello :)
I am using 
QT5.13.1,
NDK r20 
building default QtFireBase example project and build failed with error as below.
Any suggestion ? 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/0.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/1.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/2.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/3.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/4.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/7.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/8.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/9.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/10.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/11.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/12.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/13.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/14.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/15.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/16.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/17.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/18.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/19.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/20.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/21.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/22.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/23.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/24.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/25.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/26.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/27.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/28.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/29.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/30.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/31.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/32.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/33.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/34.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/35.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/36.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/37.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/38.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/39.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/40.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/41.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/42.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/43.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/44.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/45.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/46.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/47.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/48.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/49.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/50.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/51.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/52.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/53.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/54.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/55.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/56.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/57.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/58.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/59.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/60.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/61.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/62.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/63.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/64.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/65.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/66.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/67.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/68.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/69.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/70.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/71.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/72.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/73.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/74.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/75.jar, /mnt/home/piyush/devel/qt/thirdparty/build-QtFirebaseExample-Android_for_armeabi_v7a_Clang_Qt_5_13_1_for_Android_ARMv7-Release/android-build/build/intermediates/transforms/dexBuilder/debug/76.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Building the android package failed!
  -- For more information, run this command with --verbose.
18:43:59: The process "/home/piyush/devel/Qt5.13.1/5.13.1/android_armv7/bin/androiddeployqt" exited with code 14.
Error while building/deploying project QtFirebaseExample (kit: Android for armeabi-v7a (Clang Qt 5.13.1 for Android ARMv7))
When executing step "Build Android APK"
18:43:59: Elapsed time: 00:15.

**Comment by Larpon** [comment]
@piyushverma hi and welcome 🙂

Please see [this comment thread](https://github.com/Larpon/QtFirebase/issues/120#issuecomment-518783539)

**Comment by husninazer** [comment]
@piyushverma 
I had the same issue with android ndk r20 and sdk 27.  Try changing the firebase SDK to v6.1.0. It worked for me.

**Comment by piyushverma** [comment]
First of all I am really really sorry to not reply on time.
I don't know how I missed our notification from github.

And yes changing to sdk to v6.1.0 solved the issue, I will try to use further.

Thank your very much Larpon, Husninazer, for your information.
