### ISSUE TITLE
Could not determine the dependencies of task ':compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by shariatraad** [Larpon/QtFirebase#134]
Hello! I'm trying to build the example and I have followed all of the steps but I keep getting this error on my compile output, any idea how to solve this issue? 

>  FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileDebugJavaWithJavac'.
> 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.impl
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.impl
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.Fusion.impl
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.Imagine.impl
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.Imagine.impl
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.Material.impl
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.Universal.impl
Building the android package failed!
  -- For more information, run this command with --verbose.
13:05:07: The process "C:\Qt\5.13.1\android_arm64_v8a\bin\androiddeployqt.exe" exited with code 14.
Error while building/deploying project QtFirebaseExample (kit: Android for arm64-v8a (Clang Qt 5.13.1 for Android ARM64-v8a))
When executing step "Build Android APK"

**Comment by Larpon** [comment]
Hi @shariatraad - this might be a Gradle error.
Please try and update `buildToolsVersion` and `compileSdkVersion` to something more recent as suggested [here](https://stackoverflow.com/a/33404698/1904615).

**Comment by shariatraad** [comment]
Dear @Larpon I have upgraded my `gradle` to `gradle-5.4.1` , `com.android.tools.build` to `gradle:3.5.0` , `BuildToolsVersion` to `"29.0.2"` and `compileSdkVersion` to `26`. But still get the same error

**Comment by Larpon** [comment]
> Dear @Larpon I have upgraded my
> 
> `gradle` to `gradle-5.4.1`
> `com.android.tools.build` to `gradle:3.5.0`
> `BuildToolsVersion` to `"29.0.2"`
> `compileSdkVersion` to `26`.
> 
> But still get the same error

Well - that sucks :slightly_smiling_face: 
What version of the Firebase SDK are you using? Many report that `6.1.0` currently seem to have the best success rate

**Comment by Larpon** [comment]
`compileSdkVersion` should now be a minimum of `28` due to some eco-system changes. I've successfully compiled the Android version of QtFirebaseExample against Firebase C++ SDK v6.7.0

**Comment by shariatraad** [comment]
I forgot to close this issue that I opened couple of months ago which has been solved .. after playing around with gradle version, buildtool version and firebase sdk version I could compile it without any issues! Thanks for the solution Larpon!

**Comment by Larpon** [comment]
Thanks for aiding our house keeping 👍
