### ISSUE TITLE
how build on windows ?

### ISSUE THREAD

**Issue by TechComet** [Larpon/QtFirebase#136]
Hi,

Please, how build on windows easy ?

It's need much 3rd library, Tired of building them on windows

**Comment by Larpon** [comment]
Seem related to #48 ?
I'm not aware of any extra 3rd party dependencies on Windows that's not required on other supported platforms as well?

We (QtFirebase) can't do anything about the dependencies of Firebase itself. QtFirebase is a *wrapper* around a larger [C++ code base](https://github.com/firebase/firebase-cpp-sdk), nothing more, nothing less. Firebase is a Google product, they decide the functionality and thus the stack of dependencies etc. - [open an issue at their end](https://github.com/firebase/quickstart-cpp) - or contribute with better documentation or setup instructions to this project when you have something better than what we provide.

We can't do any magic to resolve you being tired of building stuff that is currently needed - I'm sorry but that's not how the world works :)

Like many other open source projects we haven't got resources to provide help for individual or personal projects. If you have anything **specific** that is not working on Windows feel free to open a specific issue and we *might* be able to help.
