### ISSUE TITLE
Debugging console

### ISSUE THREAD

**Issue by Trikos** [Larpon/QtFirebase#154]
Hi Larpoon, at the end I was able to make your app working. It was my fault because we were using AWS instead of google console to send the notification, but everything was set perfectly.
Now Im interested in the console in the app, did you develop it using qt or is something with android?
Could you released the QML page of that console (without the hot stuff), just the layout? I really need one of them for my project.
Thank you

**Comment by Larpon** [comment]
I can' t help with any specific setups. I have this code in one of my projects:
```
void messageOutput(QtMsgType type, const QMessageLogContext &context, const QString &msg)
{
    QByteArray localMsg = msg.toLocal8Bit();
    const char *file = context.file ? context.file : "";
    const char *function = context.function ? context.function : "";
    switch (type) {
    case QtDebugMsg:
        //fprintf(stderr, "Debug (%s:%u) %s: %s\n", file, context.line, function, localMsg.constData());
        break;
    case QtInfoMsg:
        fprintf(stderr, "Info (%s:%u) %s: %s\n", file, context.line, function, localMsg.constData() );
        break;
    case QtWarningMsg:
        //fprintf(stderr, "Warning (%s:%u) %s: %s\n", file, context.line, function, localMsg.constData());
        break;
    case QtCriticalMsg:
        fprintf(stderr, "Critical (%s:%u) %s: %s\n", file, context.line, function, localMsg.constData());
        break;
    case QtFatalMsg:
        fprintf(stderr, "Fatal (%s:%u) %s: %s\n", file, context.line, function, localMsg.constData());
        break;
    }

}

int main(int argc, char *argv[])
{
   qInstallMessageHandler(messageOutput);

   ... <rest of your main.cpp> ...
}
```
So instead of using `fprintf` as I do in this example - you'd send a QString off to your QML object instead.

**Comment by Trikos** [comment]
What do you mean by "send a QString off to your QML"? I would replace fprintf with MyClass.MyQString = context.line. 
Or you are referring to my main QML object that it is always a QQuickView?
`QQuickView *view = new QQuickView;

    MyClass clss;

    view->rootContext()->setContextProperty("MyClass", &clss);
    view->setSource(QUrl("qrc:/Init.qml"));
    view->setResizeMode(QQuickView::SizeRootObjectToView);
    view->show();

    return app.exec();`

**Comment by Larpon** [comment]
Whatever works I guess.

You could probably send messages via a [SingletonInstance](https://doc.qt.io/qt-5/qqmlengine.html#qmlRegisterSingletonInstance) also - there's many ways to do it I think.

If the way you're doing it currently, works - I guess there's no need to fix it :wink:

**Comment by Trikos** [comment]
Ok, perfect and thanks again

**Comment by Larpon** [comment]
@Trikos I'm glad to help :slightly_smiling_face:
