### ISSUE TITLE
Can't compile with QTFIREBASE_CONFIG += analytics messaging for iOS

### ISSUE THREAD

**Issue by 1799** [Larpon/QtFirebase#165]
Hi, 
I have just download Example and tried to compile because I want to use messaging feature of this.
if 
`QTFIREBASE_CONFIG += analytics`
It built OK.
but with
`QTFIREBASE_CONFIG += analytics messaging`
It build error with this message 

> Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_GDTCORTransport", referenced from:
      objc-class-ref in FirebaseMessaging(FIRMessagingExtensionHelper.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Anyone got this issue before.
I am using Qt 5.15.2
Latest firebase_sdk

**Comment by borisssoft** [comment]
@Larpon Fixed in #166.

**Comment by Larpon** [comment]
> @Larpon Fixed in #166.

You're a champion, thanks!
