### ISSUE TITLE
Why dont implement Admob's NativeAd

### ISSUE THREAD

**Issue by li3p** [Larpon/QtFirebase#19]
@Larpon Is there any difficulties to implement Native Ad？

[https://firebase.google.com/docs/admob/cpp/native-express](https://firebase.google.com/docs/admob/cpp/native-express)

**Comment by Larpon** [comment]
Thanks for your PR! - which platform(s) have you tested the code on so far?

**Comment by li3p** [comment]
I tested on Android only, and it works fine. Hope you can make some test on IOS devices.

**Comment by Larpon** [comment]
Super cool - I'll test on my iOS device as soon as I can :)

**Comment by li3p** [comment]
PR accepted , we can close this now.
