### ISSUE TITLE
Cant compile the example project

### ISSUE THREAD

**Issue by isipisi281** [Larpon/QtFirebase#2]
Hi together,
so i got the problem that i cant compile the example project. My include paths are all ok. 
Here a pic of my Build-Problems: https://www2.pic-upload.de/img/32896123/Error.png
Hope you can help me.
Regards Isy

**Comment by isipisi281** [comment]
Okey i fixed the problem by using the latest Firebase version.
But the App crashes after start. Here some logs: 
.
.

> D libApp.so: (null):0 ((null)): QtFirebaseAdMob(0xac032ee8) ::QtFirebaseAdMob singleton
E firebase: local_class
F firebase: Java class com/google/firebase/FirebaseApp not found.  Please verify the AAR which contains the com/google/firebase/FirebaseApp class is included in your app.
F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 8025 (QtThread)
"com.blackgrain.android.firebasetest" died.

I am using a Huawai P8 with Android 6.0

**Comment by greenfield932** [comment]
Could you please check you have installed google play services on the device?

**Comment by isipisi281** [comment]
Google-Play-Services are installed. I will try to build it under Linux now. Mybe its just an windows thing. 
Are you developing under win or linux?

**Comment by Larpon** [comment]
Hi @isipisi281

Good thing you found out you need Firebase C++ SDK >= v3.1.0 to compile the project now - the version has bumped as RemoteConfig module uses the updated version.

First off - are you using gradle to build the project?

Second it's important that your Android SDK is <= v25.2.5 (Google have removed the `android` tool which Qt uses in it's build process)

Like @greenfield932 suggests - you might double check that you have Google Services installed and updated on your device - I will update the documentation to say so as well.

**Comment by isipisi281** [comment]
Okey i got it to work now. My home pc is running with windows 10 but i dont know which Android SDK i got up to date there. With Linux at work i can build the example like charm. I will check it the issu again at home and reply to you guys. Btw grait work!

**Comment by Larpon** [comment]
I mainly test and build from Linux and MacOS - so Windows is unfortunately not at first class citizen just yet  - but Qt should make sure it works out of the box

**Comment by Larpon** [comment]
@isipisi281 - I'll close this for now. You are welcome to open a new issue based on the Windows build
