### ISSUE TITLE
Why RewardedVideoAd does not work?

### ISSUE THREAD

**Issue by li3p** [Larpon/QtFirebase#25]
I am testing `QtFirebaseRewardedVideoAd` today, but always got ：

```bash
QtFirebaseAdMobRewardedVideoAd(0x77cc9f98) ::onFutureEvent load failed ERROR code: 7 message: "No ad was available to serve."
```

I am not using it in QML but in C++ code, here is the coded related, `AdMob` is a c++ class in my own code:

```c++
m_rewardedVideoAd->setAdUnitId("ca-app-pub-3940256099942544/5224354917");
connect(m_rewardedVideoAd, &QtFirebaseAdMobRewardedVideoAd::readyChanged, this, &AdMob::onVideoAdReady);
connect(m_rewardedVideoAd, &QtFirebaseAdMobRewardedVideoAd::loadedChanged, this, &AdMob::onVideoAdLoaded);
connect(m_rewardedVideoAd, &QtFirebaseAdMobRewardedVideoAd::closed, this, &AdMob::onVideoAdClosed);
connect(m_rewardedVideoAd, &QtFirebaseAdMobRewardedVideoAd::rewarded, this, &AdMob::onVideoAdRewarded);

void AdMob::onVideoAdReady()
{
    qDebug() << "QtFirebaseAdMobRewarededVideoAd::ready";
    QtFirebaseAdMobRequest *_request = new QtFirebaseAdMobRequest(m_rewardedVideoAd);
    _request->setTestDevices(m_testDevices);
    m_rewardedVideoAd->setRequest(_request);
    m_rewardedVideoAd->load();
}

void AdMob::onVideoAdLoaded()
{
    qDebug() << "AdMob::onVideoAdLoaded";
}

void AdMob::onVideoAdClosed()
{
    qDebug() << "AdMob::onVideoAdClosed";
    m_rewardedVideoAd->load();
}

void AdMob::onVideoAdRewarded(QString type, float value)
{
    qDebug() << "AdMob::onViedoAdRewarded" << type << value;
}
```

Has anybody tested this Ad format ?  Anything was wrong in my code ?

**Comment by Larpon** [comment]
Could it be, simply, that there is no ads available to serve? I'm experiencing this from time to time. Also in other apps. Sometimes there's probably not enough video ads to cover the requested ad space.

@greenfield932 - did you bump into this when you made the implementation?

**Comment by Larpon** [comment]
Does it show test ads if you add your device ID to the `testDevices: []` property? If the test ads show it a coverage/Firebase thing - not anything we can fix

**Comment by li3p** [comment]
I am testing it with testDevices , but no ads shows.

**Comment by Larpon** [comment]
Are you still experiencing problems @li3p?

**Comment by li3p** [comment]
yes, still experiencing the problem, but may related to some VPN issues. 
Lets close this issue now, I will keep watching this problem.

**Comment by Larpon** [comment]
Cool. To me it looks like something within the SDK or simply something related to AdMob. Keep an eye on it :)
