### ISSUE TITLE
Crash reports in firebase::App::GetInstance

### ISSUE THREAD

**Issue by li3p** [Larpon/QtFirebase#29]
I published my app to Google Play Market, but By add Admob features,  the crash reports increased.
Because my phone did not crash, so I cannot determine why this happen? Does it caused by thread issues?  Any idea can help to fix this or further determine the reason?

![crash](https://user-images.githubusercontent.com/55519/29659571-4dec39ba-88f1-11e7-9c82-6f1f2a4205d3.jpg)

**Comment by li3p** [comment]
Maybe that was caused by called `QtFirebaseRemoteConfig->fetchNow` while the `QtFirebaseRemoteConfig::ready() == true`. I changed some code and will test it by publish it. #31

**Comment by li3p** [comment]
According to the report in Google Play market console, this change worked. no more crash reports generated now.

**Comment by Larpon** [comment]
It's a bit hard for me to dig deeper into this as I don't have anything real-world running using RemoteConfig. I've merged your delay PR nonetheless (as it seem to fix a lot of crashes)
