### ISSUE TITLE
Crash on Android 6.0.1 while compiling with Qt 5.8

### ISSUE THREAD

**Issue by greenfield932** [Larpon/QtFirebase#3]
I'm getting stable crash on startup if compile with Qt 5.8. Works fine on Qt 5.7+android 6.0.1

D libApp.so: (null):0 ((null)): QtFirebaseAdMob(0xab7da928) ::QtFirebaseAdMob singleton
F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 635 (QtThread)

Seems the issue in the activity handle. I'm able to workaround it but really can't explain it. 
1. In QtFirebase class
add member QAndroidJniObject m_activity;
2. init in requestInit()
if(!m_activity.isValid())
 {
            m_activity = QAndroidJniObject::callStaticObjectMethod("org/qtproject/qt5/android/QtNative", "activity", "()Landroid/app/Activity;");
}
3. Add member function 
jobject getNativeWindow(){return m_activity.object();}

All this stuff works only if m_activity is a member of QtFirebase by some reason.
Should I send pull request for it?

**Comment by Larpon** [comment]
You're more than welcome to send a pull request - I'll check if it makes a difference on my devices. When I can get to a computer. 

I've also got a weird crash on startup now on my phone I've been testing it on since the beginning. I don't know what happened :/

**Comment by greenfield932** [comment]
Not sending pull request. I have stable crash on x86 now, can't fix it, reproduced on 5.7.1-5.9, so I'm return back to 5.7

**Comment by Larpon** [comment]
Yuk :(

**Comment by greenfield932** [comment]
@Larpon please close the issue, it is most likely caused by mixing stl versions in my project. I can run with Qt 5.8 successfully now.

**Comment by Larpon** [comment]
Ok. Let's hope it stays solved then :)
