### ISSUE TITLE
RemoteConfig crashes on subsequent calls to fetch()

### ISSUE THREAD

**Issue by isipisi281** [Larpon/QtFirebase#37]
RemoteConfig crashes @ line 355 .cpp file.

As soon as this is called: 
remote_config::SetDefaults(defaults.get(), filteredMap.size());

defaults.get() and  filteredMap.size() do work fine 
defaults.get() gives a pointer and filteredMap.size() gives the count in the array setted in qml.

Tested on IOS with Firebase 4.1.0 and the latest pull.
Could someone test this if it crashes only 4 me?

**Comment by Larpon** [comment]
Are you running off master branch? I [thought](https://github.com/Larpon/QtFirebase/commit/f1c32e775d8dd7130ba7057a283e98bad2d1b979#diff-c1773a8c99827bb4b03a5512c194bbd0L355) I [fixed](https://github.com/Larpon/QtFirebase/commit/04f92b31f06c03da51903b146ec1d721193f6205#diff-c1773a8c99827bb4b03a5512c194bbd0L309) this by holding references to the strings in `__defaultsByteArrayList`?

**Comment by isipisi281** [comment]
Okey found the "bug".
If you request fetch() 2 x times back to back the app crashes.
I think there should be a property to check if there is a fechrequest ongoing.

**Comment by Larpon** [comment]
Yes there should indeed :)

**Comment by borisssoft** [comment]
@Larpon Fixed in #161.

**Comment by Larpon** [comment]
> @Larpon Fixed in #161.

Fantastic! Thanks a lot!
