### ISSUE TITLE
RemoteConfig (and other) crashes when re-initialized via QML Loader

### ISSUE THREAD

**Issue by Larpon** [Larpon/QtFirebase#42]
Currently crashes in the QtFirebaseExample app when the `Loader` loads it the second time.

Might be because of the use of ModuleInitializer?

Workaround it by having your `RemoteConfig` only initialized once per. application life-cycle

**Comment by isipisi281** [comment]
All elements should be initialized just once. Loader should be not in the usecase.

**Comment by Larpon** [comment]
I've tried asking if this is [expected behaviour](https://github.com/firebase/quickstart-cpp/issues/19)

**Comment by Larpon** [comment]
I've fixed (on Android at least) crashes related to life-cycle shutdowns in RemoteConfig and Analytics. Auth and AdMob are still awaiting Google (Auth could be something different)
