### ISSUE TITLE
Can't compile qtfirebase

### ISSUE THREAD

**Issue by nero08** [Larpon/QtFirebase#43]
Hello,

I have this error when I try to compile qtfirebase:

https://gyazo.com/114329fac0c8bd30c3f93447a014c567

**Comment by nero08** [comment]
need to include database to QTFIREBASE_CONFIG to work

**Comment by Larpon** [comment]
That's indeed a bug. The Auth and Database modules has just been contributed and merged in - so it's a slip-up from that

**Comment by Larpon** [comment]
Please re-open if the problem persist
