### ISSUE TITLE
enable to retrieve token for messaging

### ISSUE THREAD

**Issue by nero08** [Larpon/QtFirebase#45]
Hello,

I have a problem with Messeging plugin, the plugin is intialized and ready but it does not retrieve the token.

I put it in my manifest 

https://pastebin.com/cywZHPUQ

my android ndk version is 14b

I've forgot something?

**Comment by Larpon** [comment]
Can you please triple check if your setup is like the one in [QtFirebaseExample](https://github.com/Larpon/QtFirebaseExample)? The messaging module works on my Android devices with the app produced from QtFirebaseExample. (maybe fetch the project and build it with Qt Creator to see if the error persists)

**Comment by nero08** [comment]
I test and I receive notification but I can't retrieve the token, onTokenChanged is not emited and when I call messaging.token, the value is empty

**Comment by Larpon** [comment]
Any progress? I get a token on all my 4 different test devices (real devices - not emulator)

**Comment by nero08** [comment]
no, but I use a different solution, I call native code with QAndroidNative, my java file call firebase api who return the token. So it's ok

But in qml, I always don't retrieve the token, the onTokenChange is not emited

**Comment by Larpon** [comment]
Hmm. I'll leave this open for the time being. Maybe other users will encounter the same problem

**Comment by isipisi281** [comment]
Its workin on my devices fine too.
Testet on iPhone 5, iPhone 5s, iPhone 6, Galaxy S6/S7/S8.

**Comment by Furkanzmc** [comment]
I've just investigated the code after deciding to use the library in my project, and it seems that the following signals are being connected too late.

```
connect(g_listener, &MessageListener::onMessageReceived, this, &QtFirebaseMessaging::getMessage);
    connect(g_listener, &MessageListener::onTokenReceived, this, &QtFirebaseMessaging::getToken);
```

before the `componentComplete` is called, the `MessageListener` receives the token and then calls `onTokenReceived` but there's no one to respond to that signal. The solution would be to connect the signals in constructor, and then check If there's a new token and then emit the `tokenChanged` signal in `componentComplete`.

I have experience dealing with similar cases. I was using the native libraries for iOS and Android and writing wrappers around them to use FCM with my library [qutils](https://github.com/Furkanzmc/qutils). I decided to integrate QtFirebase to my project. So I'll write a solution and send a PR. But until then, the aforementioned solution should work.

**Comment by Larpon** [comment]
@Furkanzmc - you might just be absolutely correct! I've had similar scenarios back when I started the project. It's worth a try. Nice catch! Do you happen to have a patch / PR for this?

**Comment by driele-torres** [comment]
@Furkanzmc  Just yesterday, I noticed that! Then I saw your response, so I connected the signals in constructor and till now is working nicely! =D

**Comment by Larpon** [comment]
Great news!

**Comment by isipisi281** [comment]
@Furkanzmc  https://github.com/Larpon/QtFirebase/commit/534a31455cf4bdba6d8127427dadd99a0df835b3
Should be fixed with this Update.
