### ISSUE TITLE
How add QtFirebase to Qt Plugins ?

### ISSUE THREAD

**Issue by TechComet** [Larpon/QtFirebase#47]
How add QtFirebase to Qt Plugins ?

CONFIG += QtFirebase
or
QT += QtFirebase

**Comment by greenfield932** [comment]
I'm not sure is it possible to use it as a plugin, probably @Larpon  will provide details.
Simple way to start using QtFirebase in your project is just add it to your project as a subproject and add some defines related to QtFirebase, see instructions how to do it here https://github.com/Larpon/QtFirebase/blob/master/SETUP.md

**Comment by Larpon** [comment]
@TechComet - I'm not sure I follow on what you're trying to do?

It's deliberately chosen to include QtFirebase to your project via the `.pri` file. And then control what modules should be active via `QTFIREBASE_CONFIG`

Like here:
https://github.com/Larpon/QtFirebaseExample/blob/master/App/App.pro#L69-L77

**Comment by Larpon** [comment]
I finally think I understand the original question.
You ask if it's available as a Qt module ([like this](https://github.com/Skycoder42/QtDataSync#usage)).

The answer to this is: we don't support this feature yet. Include QtFirebase via the `.pri` file.
