### ISSUE TITLE
AdMob error code and message is 'undefined'

### ISSUE THREAD

**Issue by Larpon** [Larpon/QtFirebase#5]
```qml
AdMobInterstitial {
        ...
        onError: {
            // code and message == undefined
        }
    }
```
Same thing for `AdMobBanner`

**Comment by greenfield932** [comment]
Seems issue caused by code variable type (Error enum). Not sure if it is possible to send custom types in signals to qml. Atleast you can fix it by changing code type to int on cpp side.

**Comment by KORuL** [comment]
Yes, indeed, you are right with the NDK r10e application launched. The Admob banner appeared and moved when the button is clicked. However, Interstitial advertising is not shown, could you tell me how to fix it. Interstitial loading ... does not change. AdMob Banner reloaded well. 
And I try Test event logging, i push it, but in debug do not trace  in "qtfirebaseanalytics.cpp" any function call

**Comment by Larpon** [comment]
@KORuL - the "Test event logging" button is for Analytics - it sends test data to my firebase project - you should be able to see what it does in the console log output.

The interstitial is working fine on the iOS build - I think it's an AdMob / fill rate thing maybe?
I've only ever had problems on Android with both kind of banners. Sometimes they just fail.

What does the console output tell you? Any clues?

I should revamp the Example App to include buttons for forced reloads etc. - I'm not sure the app is set to reload the interstitial on error right now

**Comment by KORuL** [comment]
I рфму and this error Yes, QtFirebaseAnalytics Works well I made sure that everything was displayed in the console, and that's what brought it out: I'm confused by the following lines:W libApp.so: (null): 0 ((null)): QtFirebase (0xf37e7a00) :: processEvents processing eventsW libApp.so: (null): 0 ((null)): QtFirebase (0xf37e7a00) :: processEvents future event "0xdb8b9680.interstitial.loaded"W libApp.so: (null): 0 ((null)): QtFirebase (0xf37e7a00) :: processEvents removed future event "0xdb8b9680.interstitial.loaded" and further: W libApp.so: (null): 0 ((null)): QtFirebaseAdMobInterstitial (0xdb8b9680) :: onFutureEvent load failed ERROR code: 4 message: An internal SDK error occurred.W libApp.so: (null): 0 ((null)): Internal Error Next, I will send screenshots of all the processes:Then everything is fine

**Comment by Larpon** [comment]
´ERROR code: 4 message: An internal SDK error occurred´ <- this one indicates that there's something in Google's code that went wrong - not much we can do about it - have you tried with your own App ID's / AdUnit Ids?

**Comment by SteelProgramming** [comment]
hi @KORuL 
I had same problem with interstitial, but it's fix after adding my device to testDevices list
fine such line in log and add your UIN to your list

**Comment by InSpectrumed** [comment]
Hi.
I have tried with own App ID's / AdUnit Ids for banner - and get error message == undefined.

**Comment by Larpon** [comment]
@InSpectrumed - yeah - we need to get it fixed. If I remember correctly you should be able to see the error message in the app console/debug output

**Comment by InSpectrumed** [comment]
Hi.
and for AdMobRewardedVideoAd I get error message == ErrorInternalError.

**Comment by InSpectrumed** [comment]
Hi.
I tried to use my own IDs for the application ID / AdUnit - and now it's a success.

1. I downloaded "google-services.json" my project from Firebase and put it in the "App \ platforms \ android \" directory;
2. in build.gradle has changed
- applicationId "com.blablabla.android.firebasetest" // Used by Firebase auto-config (the google-services.json from Firebase console);

com.blablabla.android.firebasetest - took from my "google-services.json"

AdMobBanner, AdMobInterstitial, AdMobRewardedVideoAd - works.
AdMobNativeExpressAd - get error message = undefined

Thank you.
I hope prompt or correct AdMobNativeExpressAd.

**Comment by Larpon** [comment]
I have problems with AdMobNativeExpressAd on both Android and iOS as well at the moment. The error seem to reside somewhere in firebase right now (Internal SDK error) - it should probably be reported to Google. I don't have time on my hands for a deep investigation. But you are welcome to report it. Please start by looking at the console output as the error code and string are output correctly there.
