### ISSUE TITLE
Token is broken on android with the new android firebase update

### ISSUE THREAD

**Issue by isipisi281** [Larpon/QtFirebase#50]
I fixed it local. WIll push it tomorow.

**Comment by Larpon** [comment]
@isipisi281 - sounds great! Any chance it might fix #45 as well?

**Comment by isipisi281** [comment]
I think this is the same "bug". Before  it worked bcs the token was generated slower than the connection was done. Now the token generation is faster than the connection.

**Comment by Larpon** [comment]
Awesome

**Comment by isipisi281** [comment]
https://github.com/Larpon/QtFirebase/commit/534a31455cf4bdba6d8127427dadd99a0df835b3

Should be fixed with this update.
