### ISSUE TITLE
QT FIrebase on IOS Background App

### ISSUE THREAD

**Issue by cinohee** [Larpon/QtFirebase#60]
Hello,
I used qtFirebase in android without any problem
In IOS i could receive notification while app is open but when app is in background I could not receive any message.
Could you help me?

**Comment by Larpon** [comment]
Hi!
Yeah you're not alone - if you'd be so kind to describe your iOS setup (e.g. what iOS/Firebase versions are you using) - in [this issue #49 ](https://github.com/Larpon/QtFirebase/issues/49)

**Comment by Larpon** [comment]
Continued in re-opened #49
