### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by KORuL** [Larpon/QtFirebase#64]
Great job guys! You are doing a very cool thing! Thanks you!

I had such a mistake, Having built in my application the package does not subscribe, have any ideas?

**Comment by KORuL** [comment]
![image](https://user-images.githubusercontent.com/19871487/33846666-d55fe4c4-deb8-11e7-8b3f-9d15e88403ed.png)

**Comment by KORuL** [comment]
the final apk debug for some reason is not in the folder in the folder type output / apk
not in
output / apk / debug

**Comment by KORuL** [comment]
Still a question how to change push icon?
I replaced all * .png * .svg with my own, but still push with the firebaseqt

**Comment by Larpon** [comment]
@KORuL - Hi! Thanks for using out QtFirebase :)

I have lost track of your problem here - your first three comments seem to be a Qt Creator specific problem which I can't help with.

What `*.png` and `*.svg` files are we talking about?
What are you trying to "push" - and where to?

**Comment by KORuL** [comment]
Firebase Cloud Messaging (FCM) 
I changed all the icons to their own, all .svg .png. But for some reason push messages come with a firebase icon, I already recompiled, cleaned the project, did everything, and still the icon did not change. I took your example, inserted my project instead of the App leaving all androidmanifest .info plist replaced all the icons of the package name and so on. But the icon remained the same

**Comment by Larpon** [comment]
Ah I get it now. Uhm... QtFirebase doesn't handle nor use any icons inside the project - they're only there for the README.md file.

To my knowledge it seems that both Android and iOS implementations just use the icon of the application?

I've had problems with cached icons on both platforms though - so if you've used QtFirebaseExample as a base it might be a cache problem - try changing the icon of your app. It's just guess work though :)

**Comment by Larpon** [comment]
The instructions for the [Firebase Android SDK](https://firebase.google.com/docs/cloud-messaging/android/client#manifest) mention icons - but I have no idea if they will apply to QtFirebase as we rely solely on the Firebase C++ SDK

**Comment by KORuL** [comment]
Please help me figure it out. I have already tried all methods. I created a new application, corrected AndroidManifest, all icon * .png * .svg files replaced with their own, added QtFirebase, there too, replaced all the icons. I cleaned the entire C: / ProgrammData folder, deleted everything I found Total Commander on drive C by searching for * firebase *. Added to AndroidManifest
 metadata about default notification icon. Cleaned the project, started qmake, rebuilt. And still in the baground came the firebase icon with the word qt

**Comment by Larpon** [comment]
Have you checked *all* folders in `/QtFirebaseExample/App/platforms/android/res/` - this is where Android reads it's resources from

**Comment by Larpon** [comment]
Same goes for iOS:
`QtFirebaseExample/App/platforms/ios/` (*.png files)
`QtFirebaseExample/App/platforms/ios/icons/`

**Comment by KORuL** [comment]
yes, in these directories only my files with the same names

**Comment by Larpon** [comment]
That's super weird - and you have tried to uninstall the app completely before installing it again?
How about utilizing [this](https://stackoverflow.com/questions/37325051/notification-icon-with-the-new-firebase-cloud-messaging-system) - maybe try and add `res/drawable*/ic_launcher.png` like this [guy suggests](https://stackoverflow.com/a/26253860/1904615)

I haven't had any problems with this on any of my devices :/

@isipisi281 -- you have notifications running with your own icons haven't you?

**Comment by KORuL** [comment]
Everything worked. The problem was in the phone. I had to uninstall the application, reboot, and then run the program that all cleaned up. And then after passing all these steps the icon has changed. Thank you, the topic is closed.
