### ISSUE TITLE
setCurrentScreen cannot be called with the same class and name

### ISSUE THREAD

**Issue by adolby** [Larpon/QtFirebase#65]
Sometimes the warning: `setCurrentScreen cannot be called with the same class and name` is printed from Firebase Analytics. This is probably because `QtFirebaseAnalytics::setCurrentScreen(const QString &screenName, const QString &screenClass)`currently takes a screen name and screen class as parameters but then uses the screenName parameter twice when it calls `analytics::SetCurrentScreen`.

**Comment by Larpon** [comment]
Hmm.. good catch - I haven't seen this in my own apps

**Comment by Larpon** [comment]
@adolby - just reopen if it's not fixed
