### ISSUE TITLE
androiddeplyqt crashing: NullPointerException

### ISSUE THREAD

**Issue by vigilanz** [Larpon/QtFirebase#68]
Hello,

I'm trying to use this in one of my apps. The build itself seems to complete, though as a final step, the androiddeployqt runs into trouble:

23:08:19: Starting: "/home/flo/Qt/5.9.2/android_armv7/bin/androiddeployqt" --input /home/flo/bb/build-ceemii-app-Android_for_armeabi_v7a_GCC_4_9_Qt_5_9_2_for_Android_armv7-Debug/android-libceemii-app.so-deployment-settings.json --output /home/flo/bb/build-ceemii-app-Android_for_armeabi_v7a_GCC_4_9_Qt_5_9_2_for_Android_armv7-Debug/android-build --deployment bundled --android-platform android-27 --jdk /usr/lib/jvm/java-8-openjdk-amd64 --gradle
Generating Android Package
  Input file: /home/flo/bb/build-ceemii-app-Android_for_armeabi_v7a_GCC_4_9_Qt_5_9_2_for_Android_armv7-Debug/android-libceemii-app.so-deployment-settings.json
  Output directory: /home/flo/bb/build-ceemii-app-Android_for_armeabi_v7a_GCC_4_9_Qt_5_9_2_for_Android_armv7-Debug/android-build/
  Application binary: /home/flo/bb/build-ceemii-app-Android_for_armeabi_v7a_GCC_4_9_Qt_5_9_2_for_Android_armv7-Debug/libceemii-app.so
  Android build platform: android-27
  Install to device: No
Warning: QML import could not be resolved in any of the import paths: com.ameba
Warning: QML import could not be resolved in any of the import paths: QtQuick.Extras.Private.CppUtils
Warning: QML import could not be resolved in any of the import paths: QtQuick.Extras.Private.CppUtils
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.impl
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.Material.impl
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.Universal.impl
QtFirebase using Firebase C++ SDK located in /home/flo/bb/ceemii-app/firebase_cpp_sdk (from system property firebase_cpp_sdk.dir)
QtFirebase (Firebase C++ SDK) using Android NDK located in /home/flo/tmp/ndk/android-ndk-r13 (from system property ndk_dir)
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android-build'.
> java.lang.NullPointerException (no error message)

I tried this with QtCreator 4.5.0 on Qt 5.9.2 on a Linux host. NDK version is r13. Maybe you can point me to one direction what went wrong here? It does not seem to be an issue with the system itself, as your example program perfectly generates an APK. What i noticed though is that ... yours seemed to download and install a different gradle (4.1) while mine used 3.4

I have no idea what caused your example to fetch that 4.1 version ... maybe that would solve the issue already?

**Comment by vigilanz** [comment]
OK so after some googling and looking at my files, I found out the cause for this was a bad NDK path in one of the files (only in local.properties, ndk.dir) - that one is not captured by your NDK detection. So if someone googles here: Make sure your NDK path is correct in both files.

**Comment by Larpon** [comment]
@vigilanz - Thanks for trying out QtFirebase - and a good thing you've solved the problem.
