### ISSUE TITLE
Compile errors need help

### ISSUE THREAD

**Issue by skimmer30** [Larpon/QtFirebase#72]
When following the steps for the example to build for ios I get some errors while compiling. 

First is a header file is not found:
extensions/QtFirebase/src/ios/Firebase/Firebase.h:1:9: fatal error: 'FirebaseAnalytics/FirebaseAnalytics.h' file not found
#import <FirebaseAnalytics/FirebaseAnalytics.h>

I commented the import out and then I get linking errors, below is the output. Any help is greatly appreciated.

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in FirebaseMessaging(FIRMessaging+FIRApp_990c986890993e9ee1072f08cac17bb3.o)
  "_kServiceInfoFileName", referenced from:
      -[FIRMessaging(FIRApp) exitApp:withError:] in FirebaseMessaging(FIRMessaging+FIRApp_990c986890993e9ee1072f08cac17bb3.o)
  "_kServiceInfoFileType", referenced from:
      -[FIRMessaging(FIRApp) exitApp:withError:] in FirebaseMessaging(FIRMessaging+FIRApp_990c986890993e9ee1072f08cac17bb3.o)
  "_kFIRAppIsDefaultAppKey", referenced from:
      +[FIRMessaging(FIRApp) didReceiveConfigureSDKNotification:] in FirebaseMessaging(FIRMessaging+FIRApp_990c986890993e9ee1072f08cac17bb3.o)
  "_kFIRAppNameKey", referenced from:
      +[FIRMessaging(FIRApp) didReceiveConfigureSDKNotification:] in FirebaseMessaging(FIRMessaging+FIRApp_990c986890993e9ee1072f08cac17bb3.o)
  "_kFIRAppReadyToConfigureSDKNotification", referenced from:
      +[FIRMessaging(FIRApp) load] in FirebaseMessaging(FIRMessaging+FIRApp_990c986890993e9ee1072f08cac17bb3.o)
  "_FIRLogBasic", referenced from:
      -[FIRMessagingLogger logFuncDebug:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_790219f59b0990edc1544b20c012dab3.o)
      -[FIRMessagingLogger logFuncInfo:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_790219f59b0990edc1544b20c012dab3.o)
      -[FIRMessagingLogger logFuncNotice:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_790219f59b0990edc1544b20c012dab3.o)
      -[FIRMessagingLogger logFuncWarning:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_790219f59b0990edc1544b20c012dab3.o)
      -[FIRMessagingLogger logFuncError:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_790219f59b0990edc1544b20c012dab3.o)
  "_OBJC_CLASS_$_FIRReachabilityChecker", referenced from:
      objc-class-ref in FirebaseMessaging(FIRMessaging_deafbc79d85e7151d21253034afabe34.o)
  "_kFIRServiceMessaging", referenced from:
      -[FIRMessaging(FIRApp) configureMessaging:] in FirebaseMessaging(FIRMessaging+FIRApp_990c986890993e9ee1072f08cac17bb3.o)
      -[FIRMessaging(FIRApp) exitApp:withError:] in FirebaseMessaging(FIRMessaging+FIRApp_990c986890993e9ee1072f08cac17bb3.o)
  "typeinfo for firebase::messaging::Listener", referenced from:
      typeinfo for MessageListener in moc_qtfirebasemessaging.o
  "vtable for firebase::messaging::Listener", referenced from:
      firebase::messaging::Listener::Listener() in qtfirebasemessaging.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "_OBJC_CLASS_$_FIRInstanceID", referenced from:
      objc-class-ref in FirebaseMessaging(FIRMessaging_deafbc79d85e7151d21253034afabe34.o)
  "firebase::messaging::Listener::~Listener()", referenced from:
      MessageListener::~MessageListener() in moc_qtfirebasemessaging.o
  "firebase::messaging::Terminate()", referenced from:
      QtFirebaseMessaging::~QtFirebaseMessaging() in qtfirebasemessaging.o
  "_kFirebaseCloudMessagingErrorDomain", referenced from:
      -[FIRMessaging(FIRApp) configureMessaging:] in FirebaseMessaging(FIRMessaging+FIRApp_990c986890993e9ee1072f08cac17bb3.o)
      -[FIRMessaging(FIRApp) exitApp:withError:] in FirebaseMessaging(FIRMessaging+FIRApp_990c986890993e9ee1072f08cac17bb3.o)
  "firebase::App::Create(firebase::AppOptions const&)", referenced from:
      QtFirebase::requestInit() in qtfirebase.o
  "_kFIRLoggerMessaging", referenced from:
      -[FIRMessagingLogger logFuncDebug:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_790219f59b0990edc1544b20c012dab3.o)
      -[FIRMessagingLogger logFuncInfo:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_790219f59b0990edc1544b20c012dab3.o)
      -[FIRMessagingLogger logFuncNotice:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_790219f59b0990edc1544b20c012dab3.o)
      -[FIRMessagingLogger logFuncWarning:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_790219f59b0990edc1544b20c012dab3.o)
      -[FIRMessagingLogger logFuncError:messageCode:msg:] in FirebaseMessaging(FIRMessagingLogger_790219f59b0990edc1544b20c012dab3.o)
  "firebase::messaging::Initialize(firebase::App const&, firebase::messaging::Listener*)", referenced from:
      QtFirebaseMessaging::init() in qtfirebasemessaging.o
  "firebase::g_messaging_initializer", referenced from:
      firebase::messaging_ref in qtfirebase_register.o
      firebase::messaging_ref in qtfirebasemessaging.o
      firebase::messaging_ref in moc_qtfirebasemessaging.o
ld: symbol(s) not found for architecture x86_64

**Comment by skimmer30** [comment]
I downloaded the c++ sdk and set the variable to point to it in my .pro file

QTFIREBASE_SDK_PATH = /Users/bruce/firebase_cpp_sdk
QTFIREBASE_CONFIG += messaging
include(extensions/QtFirebase/qtfirebase.pri)

I ran the download_firebase_ios.sh from the extensions/QtFirebase/src/ios directory which downloaded all the frameworks under a Firebase directory

Do I need to run with cocoapods?

**Comment by skimmer30** [comment]
Finally got the example to compile and run on my phone.

Had to add:
QTFIREBASE_CONFIG += analytics messaging

Also need to add the StoreKit framework to the qtfirebase_target.pri

**Comment by Larpon** [comment]
Thanks for clearifying - I'll look into why it suddenly need StoreKit

**Comment by Larpon** [comment]
> Do I need to run with cocoapods?
Nope - we've chosen not to use cocoapods because packages are often outdated. Hence we ask you to download the iOS SDK  to get the latest matching frameworks
