### ISSUE TITLE
Admob: test ads not working due to "An internal SDK error"

### ISSUE THREAD

**Issue by daljit97** [Larpon/QtFirebase#77]
I was able to integrate QtFirebase in my project. I copied the code from the example provided to display a banner ad in my application. When I use the test ad unit ID, the test ad is working as expected, however then I added my own devices to the list of test devices and tried to use my own ad unit ID  and I get this:
`QtFirebaseAdMobBase::load()::<lambda(const firebase::FutureBase&)>): QtFirebaseAdMobBanner(0xcc534ca0) ::load load failed ERROR code: 4 message: An internal SDK error occurred.
D Notizie : qrc:/main.qml:105 (onError): qml: Banner failed with error code 4 and message An internal SDK error occurred.`
I am not sure how I can fix the problem. This makes me think that ads won't even work in real apps published in the Play Store or App store

**Comment by Larpon** [comment]
Hey @daljit97 - thanks for trying QtFirebase. I'm affraid the problem is out our hands to fix. It's something in Google's code that causes these messages.

I have a phone where it does the same :-/

The good thing is that it only seem to affect test ids - i.e. on real devices you'll get ads if you have fill rate.

**Comment by pradeephyd** [comment]
Hi I faced the similar issue.. I solved this in qml make banner visible true.

**Comment by daljit97** [comment]
@pradeephyd do you mean setting `visible: true` in qml?

**Comment by pradeephyd** [comment]
@daljit97 yes

**Comment by Larpon** [comment]
@pradeephyd - interesting workaround. Maybe it's because the banners I've tested - have started out as `visible: false` - thanks for your input!

**Comment by daljit97** [comment]
Yes, I can confirm that setting `visible: true` the error is gone. However, for some reason the ad banner is not visible in my application. 
`
I Ads     : Ad finished loading.
D Notizie : ../Notizie2/extensions/QtFirebase/src/qtfirebaseadmob.cpp:586 (QtFirebaseAdMobBase::load()::<lambda(const firebase::FutureBase&)>): QtFirebaseAdMobBanner(0xcdb2ec00) ::load loaded
D Notizie : ../Notizie2/extensions/QtFirebase/src/qtfirebaseadmob.cpp:816 (virtual firebase::FutureBase QtFirebaseAdMobBanner::moveToInternal(QtFirebaseAdMobBannerBase::Position)):`

**Comment by pradeephyd** [comment]
@daljit97 check your device id properly in banner. I hope it should solve the issue.
 `AdMob {
        appId: "AppID"

        // NOTE All banners and interstitials will use this list
        // unless they have their own testDevices list specified
        testDevices: [
            "24FA72E7C35D84067AC08CC7B64B6FAD"
        ]
    }
`
Im using this way which is working fine [https://play.google.com/store/apps/details?id=org.webmate.com](url)  this is my app link in playstore.

**Comment by daljit97** [comment]
@pradeephyd For some strange reason, setting
`        onLoadedChanged: {
            if(loaded)
            {
                moveTo(AdMobBanner.PositionBottomCenter)
                visible = true
            }

        }`
made it work. Also, is it possible to place the banner inside a `Flickable` and show only when scrolling or does it have to be visible all the time?

**Comment by Larpon** [comment]
@daljit97 - you can't overlay ads with anything.

It's like that to prevent fraud I guess

**Comment by daljit97** [comment]
@Larpon yeah that makes sense. Are Native Ads supported by QtFirebase?

**Comment by Larpon** [comment]
@daljit97 - Native Express ads are deprecated by Google from SDK v5.x+ so I've chosen to remove our implementaion in master.

It should be possible to have as many banners as Google allow :relaxed:

**Comment by Larpon** [comment]
You can use Native express with 4.x and QtFirebase (a few commits back)

**Comment by daljit97** [comment]
Alright thank you
