### ISSUE TITLE
How to make subscribe to topic for Firebase cloud messaging

### ISSUE THREAD

**Issue by pradeephyd** [Larpon/QtFirebase#78]
Hi, I have integrated QtFirebase successfully to my application and uploaded in Playstore everything is working fine and i really appreciate the contributors for helping to develop apps very quickly. 
I need any docs or example to implement subscription for topics in Firebase cloud messaging.
one more issue i found in my app whenever the user clicks on the notification, one more notification is displaying with 'userclick true'  message.

**Comment by Larpon** [comment]
> I have integrated QtFirebase successfully to my application

I'm glad to hear!

> i really appreciate the contributors for helping to develop apps very quickly

You're welcome!

The documentation I use (also when expanding QtFirebase with new features) resides [here](https://firebase.google.com/docs/) (the C++ parts). The only thing I could find on cloud messaging was [this](https://firebase.google.com/docs/cloud-messaging/cpp/topic-messaging).

If you're looking for something server-side I'm not sure where to send you - but there should be plenty of examples out there.

Regarding the extra notification - I'm not sure what's happening. It's not happening in the `QtFirebaseExample` app I use as feature reference?

**Comment by pradeephyd** [comment]
@Larpon  Hi i didn't see the implementation of **Subscribe** function in qtfirebasemessaging.h i think need to add **messaging::Subscribe()** in   qtfirebasemessaging.h. Thank you.
And any plan to implement Facebook ads sdk  :)

**Comment by Larpon** [comment]
Yeah - I think it might be left out - to avoid getting too specific on how you guys use topics.

No plans on Facebook ads at the moment :-)
