### ISSUE TITLE
How to solve gradle 3.0.0 (3.0.1) issues

### ISSUE THREAD

**Issue by MohammadKanan** [Larpon/QtFirebase#85]
To get FireBase functional (Android), i am using Gradle 3.0.0 as directed by , but I encountered enormous issues with this Gradle (It still seems not adapted by Qt!) , the output structure of this Gradle is not identified by Qt build (apk goes in `apk/debug/` folder which Qt does not scan while installing on device) this can be corrected by gradle tools. But the big issue is with QML types:

`Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.impl`

**Comment by Larpon** [comment]
@MohammadKanan please see https://github.com/Larpon/QtFirebaseExample/issues/12

**Comment by MohammadKanan** [comment]
Currently only solution is to I fall back to gradle 2.3.3 (use `compile ` instead of new syntax `implementation`). I can see that with Gradle 3 and above Qt does not comply .. I noticed `strip` issues and this could be the reason for QML issues mentioned above. with gradle2.3.3 I could compile (if you import controls2 and sub types, the issues will prevent correct compile).
