### ISSUE TITLE
Is it possible to send push notifications while the app is not open?

### ISSUE THREAD

**Issue by daljit97** [Larpon/QtFirebase#89]
So I would like to send a custom notification using Firebase (like for example an update in my app) so that when the user can click notification in order to open the app. With QtFirebase is this possible? Can an app receive notifications even when closed? Reading on the Firebase docs it seems possible, but I am not sure about QtFirebase.

**Comment by rmallah** [comment]
Hi Daljit ,  Yes The notifications are received by the Firebase Services
that are independent of your App. Even if your app is *completely* closed
the FireBase receives the notification based on fcm_token or any kind of
targeting. The Firebase console provides a way to test
all these. Using fcm_token to target the device is a easy way.

**Comment by daljit97** [comment]
@rmallah one last question before I close this issue, how I can set up a custom icon for notifications received when the app is closed?

**Comment by daljit97** [comment]
Ok I figured that the way to set up a custom icons is exactly the same as on Android Java and modify the manifest file(for Oreo you also need to configure Notification Channels).

**Comment by Larpon** [comment]
@daljit97 I'm glad you finally got it working. Have you documented the process? If so you're more than welcome to leave it here for future users!

**Comment by daljit97** [comment]
@Larpon sorry for the late reply. Here is what I had to:
Ok so I found a solution to my problem. The issue was that I was testing the application on Android 8.0 Oreo. From this version of Android, Google requires that application make use of [Notification Channels][1] and applications are required to create a default Notification Channel. So I added the following code to the main activity of my application in the `onCreate` method:

    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        // Create channel to show notifications.
        String channelId  = getString(R.string.default_notification_channel_id);
        String channelName = getString(R.string.default_notification_channel_name);
        NotificationManager notificationManager =
                getSystemService(NotificationManager.class);
        notificationManager.createNotificationChannel(new NotificationChannel(channelId,
                channelName, NotificationManager.IMPORTANCE_LOW));
    }

Then added the default notification id in the manifest file:

    <meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="@string/default_notification_channel_id"/>

  [1]: https://developer.android.com/guide/topics/ui/notifiers/notifications#ManageChannels
