### ISSUE TITLE
Win 10, Qt5.8 Example project can't start - "Java class com/google/firebase/FirebaseApp not found"

### ISSUE THREAD

**Issue by SteelProgramming** [Larpon/QtFirebase#9]
Hi @Larpon 
first of all, thank you for your project.
I catch exception when I try build example project, same as @isipisi281
"Java class com/google/firebase/FirebaseApp not found.  Please verify the AAR which contains the com/google/firebase/FirebaseApp class is included in your app."
looks like I forget something small, but I can't found problem by myself

My environment: 
Qt 5.8, Win 10, 
SDK Tool 25.2.3 
SDK google play services 40
NDK r10e
Device with Android 5.0.1

thanks for help

**Comment by SteelProgramming** [comment]
same problem with android 7.0
Application start - show splash screen - raise exception ((

**Comment by Larpon** [comment]
@SteelProgramming - hi! Thanks for trying it out :)

Judging from this message: `Please verify the AAR which contains the com/google/firebase/FirebaseApp class is included in your app` - it seems like the build system hasn't included the right package(s) - could you please double check if you are using `Gradle` to build the project?

**Comment by SteelProgramming** [comment]
thank you for answer 
I'll check

**Comment by SteelProgramming** [comment]
yep, my fault((
I was confident that Gradle was enabled 
thank you for help
problem solved

**Comment by Larpon** [comment]
Awesome - I'm glad it works on Windows as well!
